### ISSUE TITLE
Name of Morpheus database isn't morpheus in my implementation

### ISSUE THREAD

**Issue by ianrscottexp** [spoonboy-io/dozer#2]
It would be very useful to have the option of passing in the name of the database in the mysql.env file.  Something like MYSQL_DATABASE=morpheusdb.

I am on version 5.4.12 of Morpheus and the name of the database is morpheusdb, not morpheus

**Comment by olliephillips** [comment]
Hi, yes, will add this. Thank you for the feedback 👍
