### ISSUE TITLE
Database poll error

### ISSUE THREAD

**Issue by sovereign313** [spoonboy-io/dozer#4]
Getting:

ERROR: Database poll err (sql: Scan error on column index 2, name "sub_type": converting driver.Value type []uint8 ("taskSet") to a int64: invalid syntax)

Morpheus version 5.4.15-2

**Comment by sovereign313** [comment]
RHEL 7 
standalone

`+-------------------------+---------------+------+-----+---------+----------------+
| Field                   | Type          | Null | Key | Default | Extra          |
+-------------------------+---------------+------+-----+---------+----------------+
| id                      | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| process_type_name       | varchar(255)  | YES  |     | NULL    |                |
| sub_type                | varchar(255)  | YES  |     | NULL    |                |
| updated_by_id           | bigint(20)    | YES  |     | NULL    |                |
| container_id            | bigint(20)    | YES  | MUL | NULL    |                |
| date_created            | datetime      | NO   |     | NULL    |                |
| server_name             | varchar(255)  | YES  |     | NULL    |                |
| last_updated            | datetime      | NO   |     | NULL    |                |
| server_group_name       | varchar(255)  | YES  |     | NULL    |                |
| created_by_id           | bigint(20)    | YES  |     | NULL    |                |
| process_type_id         | bigint(20)    | NO   | MUL | NULL    |                |
| deleted                 | bit(1)        | YES  |     | NULL    |                |
| sub_id                  | bigint(20)    | YES  |     | NULL    |                |
| updated_by              | varchar(255)  | NO   |     | NULL    |                |
| unique_id               | varchar(255)  | NO   |     | NULL    |                |
| timer_category          | varchar(255)  | YES  |     | NULL    |                |
| percent                 | double        | YES  |     | NULL    |                |
| updated_by_display_name | varchar(255)  | YES  |     | NULL    |                |
| error                   | longtext      | YES  |     | NULL    |                |
| reason                  | varchar(1000) | YES  |     | NULL    |                |
| app_name                | varchar(255)  | YES  |     | NULL    |                |
| end_date                | datetime      | YES  |     | NULL    |                |
| created_by_display_name | varchar(255)  | YES  |     | NULL    |                |
| success                 | bit(1)        | YES  |     | NULL    |                |
| duration                | bigint(20)    | YES  |     | NULL    |                |
| display_name            | varchar(255)  | YES  |     | NULL    |                |
| instance_name           | varchar(255)  | YES  |     | NULL    |                |
| input                   | text          | YES  |     | NULL    |                |
| zone_id                 | bigint(20)    | YES  | MUL | NULL    |                |
| start_date              | datetime      | YES  | MUL | NULL    |                |
| app_id                  | bigint(20)    | YES  | MUL | NULL    |                |
| message                 | longtext      | YES  |     | NULL    |                |
| server_id               | bigint(20)    | YES  | MUL | NULL    |                |
| ref_type                | varchar(255)  | NO   | MUL | NULL    |                |
| exit_code               | varchar(255)  | YES  |     | NULL    |                |
| integration_id          | bigint(20)    | YES  | MUL | NULL    |                |
| ref_id                  | bigint(20)    | NO   | MUL | NULL    |                |
| container_name          | varchar(255)  | YES  |     | NULL    |                |
| server_group_id         | bigint(20)    | YES  | MUL | NULL    |                |
| instance_id             | bigint(20)    | YES  | MUL | NULL    |                |
| output                  | longtext      | YES  |     | NULL    |                |
| created_by              | varchar(255)  | NO   |     | NULL    |                |
| status                  | varchar(255)  | YES  |     | NULL    |                |
| process_result          | varchar(1000) | YES  |     | NULL    |                |
| api_key                 | varchar(255)  | YES  |     | NULL    |                |
| account_id              | bigint(20)    | NO   | MUL | NULL    |                |
| description             | varchar(255)  | YES  |     | NULL    |                |
| status_eta              | bigint(20)    | YES  |     | NULL    |                |
| timer_sub_category      | varchar(255)  | YES  |     | NULL    |                |
| output_format           | varchar(255)  | YES  |     | NULL    |                |
| input_format            | varchar(255)  | YES  |     | NULL    |                |
| event_title             | varchar(255)  | YES  |     | NULL    |                |
| job_template_id         | bigint(20)    | YES  | MUL | NULL    |                |
| task_set_name           | varchar(255)  | YES  |     | NULL    |                |
| job_template_name       | varchar(255)  | YES  |     | NULL    |                |
| task_set_id             | bigint(20)    | YES  | MUL | NULL    |                |
| task_id                 | bigint(20)    | YES  | MUL | NULL    |                |
| task_name               | varchar(255)  | YES  |     | NULL    |                |
+-------------------------+---------------+------+-----+---------+----------------+Collapsehas context menuComposeParagraph`

**Comment by olliephillips** [comment]
Same 58 rows but a different order. Good fun! I was lazy and used a wildcard `select *` - in hindsight not the best idea. The fix is to change that select query to column names explicitly and fix the order. I can sort this as soon as I get chance. Thanks for feeding back

**Comment by olliephillips** [comment]
There's code in branch issue4. I've done some basic testing myself and does what it did before. 
There's a Linux build you can download and try on RHEL [here](https://github.com/spoonboy-io/dozer/blob/issue4/dozer)

**Comment by sovereign313** [comment]
Yup that fixed the issue!
